services:
  account-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    environment:
      TZ: ${TZ:-America/Sao_Paulo}
      URL: ${URL}
      REDIS_URL: ${REDIS_URL}
      CANARY_DB_HOST: ${CANARY_DB_HOST}
      CANARY_DB_PORT: ${CANARY_DB_PORT}
      CANARY_DB_NAME: ${CANARY_DB_NAME}
      CANARY_DB_USER: ${CANARY_DB_USER}
      CANARY_DB_PASSWORD: ${CANARY_DB_PASSWORD}
      CANARY_SERVER_NAME: ${CANARY_SERVER_NAME}
      CANARY_SERVER_IP: ${CANARY_SERVER_IP}
      CANARY_SERVER_LOCATION: ${CANARY_SERVER_LOCATION}
      CANARY_GAME_PORT: ${CANARY_GAME_PORT}
      CANARY_STATUS_PORT: ${CANARY_STATUS_PORT}
      CANARY_STATUS_TIMEOUT: ${CANARY_STATUS_TIMEOUT}
      SITE_NAME: ${SITE_NAME}
      MAINTENANCE: ${MAINTENANCE}
      DEV_MODE: ${DEV_MODE}
      MULTI_WORLD: ${MULTI_WORLD}
      M_COST: ${M_COST}
      T_COST: ${T_COST}
      PARALLELISM: ${PARALLELISM}
      OUTFITS_FOLDER: ${OUTFITS_FOLDER}
      PAGSEGURO_EMAIL: ${PAGSEGURO_EMAIL}
      PAGSEGURO_TOKEN: ${PAGSEGURO_TOKEN}
      MERCADOPAGO_TOKEN: ${MERCADOPAGO_TOKEN}
      MERCADOPAGO_KEY: ${MERCADOPAGO_KEY}
      MERCADOPAGO_CLIENTID: ${MERCADOPAGO_CLIENTID}
      MERCADOPAGO_SECRET: ${MERCADOPAGO_SECRET}
      PAYPAL_CLIENTID: ${PAYPAL_CLIENTID}
      PAYPAL_SECRET: ${PAYPAL_SECRET}
      MAIL_SMTP: ${MAIL_SMTP}
      MAIL_WEB: ${MAIL_WEB}
      RESEND_API_KEY: ${RESEND_API_KEY}
